config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  resources :groups
  root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'concerts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
    has_many  :concerts, dependent: :destroy
    enum gender: { Hombres: 0, Mujeres: 1, Banda: 3 }
    accepts_nested_attributes_for :concerts
    def to_s
        "#{name}"
    end
    def concert_count
        self.concerts.count
    end
    def concert_participant
        self.concerts
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
    @group= Group.all
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
    @groups = Group.all
  end

  # GET /concerts/1/edit
  def edit
    @groups = Group.all
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:date_concert, :participant, :duration, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :set_selects, only: %i[new edit create update]


  # GET /groups or /groups.json
  def index
    @groups = Group.eager_load(:concerts)
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selects
      @genders = Group.genders.keys.to_a
    end

    
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:member, :debut_date, :gender, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_concert %>
    <%= form.date_select :date_concert %>
  </div>

  <div class="field">
    <%= form.label :participant %>
    <%= form.number_field :participant %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Date concert</th>
      <th>Participant</th>
      <th>Duration</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.date_concert %></td>
        <td><%= concert.participant %></td>
        <td><%= concert.duration %></td>
        <td><%= concert.group %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Concierto', new_concert_path %>
<%= link_to 'Nuevo Grupo', new_group_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date concert:</strong>
  <%= @concert.date_concert %>
</p>

<p>
  <strong>Participant:</strong>
  <%= @concert.participant %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @concert.duration %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Miembros %>
    <%= form.number_field :member %>
  </div>

  <div class="field">
    <%= form.label :'Fecha Debut' %>
    <%= form.date_select :debut_date %>
  </div>

    <div class="field">
        <%= form.label :gender, "Genero" %>
        <%= form.select :gender, options_for_select(@genders)%>
      </div>




  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grupos y Conciertos</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Miembros</th>
      <th>Fecha debut</th>
      <th>Genero</th>
      <th>Conciertos</th>
      <th>Cantidad de personas</th>
      <th>Fecha Concierto</th>
      <th>id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.member %></td>
        <td><%= group.debut_date %></td>
        <td><%= group.gender %></td>
        <td><%= group.concert_count%></td>
        <td>
          <ul><% group.concerts.each do |concert|%>  
              <li><%=concert.participant %> </li>
              <%end%>
          </ul> 
        </td>
        <td>
          <ul><% group.concerts.each do |concert|%>  
              <li><%=concert.date_concert %> </li>
              <%end%>
          </ul>
        </td>
    
        <td>
          <ul><% group.concerts.each do |concert|%>  
              <li><%=concert.id %> </li>
              <%end%>
          </ul>
        </td>

        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Concierto', new_concert_path %>
<%= link_to 'Nuevo Grupo', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @group.member %>
</p>

<p>
  <strong>Debut date:</strong>
  <%= @group.debut_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @group.gender %>
</p>

<p>
  <strong>concert:</strong>
  <% mes = Time.now.month %>
  <% x= 0 %>
  <% @group.concerts.each do |concert|%>
      <%if concert.date_concert.month == mes %>
        <% x+= 1%>
      <%end%>
  <%end%>
  <%= x %>
</p>

<p>


<strong>Last event:</strong>
  <% last_date = Date.new(0000-00-00) %>
  <% @group.concerts.each do |concert| %>
    <% if concert.date_concert > last_date %>
      <% last_date = concert.date_concert %>
    <% end %>
  <% end %>
  <%= last_date.strftime("%Y %B %A") %>
</p>

<p>
<strong>Numero maximo:</strong>
<% numebermax = 0 %>
  <% @group.concerts.each do |concert| %>
    <% if concert.participant > numebermax %>
      <%  numebermax = concert.participant%>
    <% end %>
  <% end %>
  <%= numebermax %>
</p> 

<strong>Duracion maxima:</strong>
<% duracion = 0 %>
  <% @group.concerts.each do |concert| %>
    <% if concert.duration > duracion %>
      <%  duracion= concert.duration%>
    <% end %>
  <% end %>
  <%= duracion %>
</p> 


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventproducer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>